package casestudies.commonsmath4;

import org.junit.FixMethodOrder;
import org.junit.Test;
import org.junit.runners.MethodSorters;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class IntervalcheckPoint4Suite0 {

  public static boolean debug = false;

  @Test
  public void test001() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test001"); }


    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.0d, 0.0d);

  }

  @Test
  public void test002() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test002"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.1d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test003() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test003"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test004() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test004"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test005() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test005"); }


    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.0d, 0.1d);

  }

  @Test
  public void test006() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test006"); }


    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.1d, 0.1d);

  }

  @Test
  public void test007() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test007"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test008() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test008"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test009() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test009"); }


    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.0d, 0.2d);

  }

  @Test
  public void test010() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test010"); }


    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.1d, 0.2d);

  }

  @Test
  public void test011() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test011"); }


    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.2d);

  }

  @Test
  public void test012() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test012"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.2d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test013() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test013"); }


    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.0d, 0.3d);

  }

  @Test
  public void test014() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test014"); }


    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.1d, 0.3d);

  }

  @Test
  public void test015() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test015"); }


    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.3d);

  }

  @Test
  public void test016() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test016"); }


    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.3d);

  }

  @Test
  public void test017() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test017"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.1d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test018() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test018"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test019() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test019"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test020() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test020"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test021() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test021"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test022() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test022"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.2d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test023() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test023"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.1d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test024() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test024"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test025() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test025"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test026() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test026"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test027() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test027"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test028() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test028"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.2d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test029() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test029"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.1d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test030() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test030"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test031() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test031"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test032() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test032"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test033() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test033"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test034() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test034"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.2d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test035() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test035"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.1d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test036() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test036"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test037() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test037"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test038() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test038"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test039() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test039"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test040() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test040"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.2d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test041() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test041"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.1d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test042() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test042"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test043() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test043"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test044() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test044"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test045() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test045"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test046() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test046"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.2d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test047() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test047"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.1d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test048() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test048"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test049() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test049"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test050() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test050"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test051() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test051"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test052() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test052"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.2d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test053() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test053"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.1d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test054() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test054"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test055() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test055"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test056() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test056"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test057() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test057"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test058() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test058"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.2d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test059() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test059"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.1d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test060() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test060"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test061() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test061"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test062() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test062"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test063() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test063"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test064() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test064"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.2d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test065() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test065"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.1d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test066() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test066"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test067() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test067"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test068() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test068"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test069() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test069"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test070() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test070"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.2d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test071() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test071"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.1d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test072() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test072"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test073() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test073"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test074() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test074"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test075() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test075"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test076() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test076"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.2d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test077() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test077"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.1d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test078() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test078"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test079() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test079"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test080() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test080"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test081() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test081"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test082() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test082"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.2d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test083() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test083"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.1d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test084() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test084"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test085() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test085"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test086() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test086"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test087() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test087"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test088() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test088"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.2d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test089() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test089"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.1d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test090() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test090"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test091() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test091"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test092() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test092"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test093() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test093"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test094() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test094"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.2d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test095() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test095"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.1d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test096() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test096"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test097() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test097"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test098() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test098"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test099() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test099"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test100() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test100"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.2d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test101() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test101"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.1d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test102() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test102"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test103() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test103"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test104() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test104"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test105() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test105"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test106() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test106"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.2d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test107() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test107"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.1d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test108() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test108"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test109() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test109"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test110() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test110"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test111() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test111"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test112() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test112"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.2d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test113() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test113"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.1d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test114() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test114"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test115() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test115"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test116() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test116"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test117() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test117"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test118() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test118"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.2d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test119() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test119"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.1d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test120() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test120"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test121() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test121"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test122() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test122"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test123() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test123"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test124() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test124"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.2d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test125() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test125"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.1d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test126() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test126"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test127() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test127"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.0d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test128() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test128"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test129() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test129"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.1d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test130() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test130"); }


    // The following exception was thrown during execution in test generation
    try {
    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.2d);
      org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException");
    } catch (java.lang.IllegalArgumentException e) {
      // Expected exception.
      if (! e.getClass().getCanonicalName().equals("java.lang.IllegalArgumentException")) {
        org.junit.Assert.fail("Expected exception of type java.lang.IllegalArgumentException, got " + e.getClass().getCanonicalName());
      }
    }

  }

  @Test
  public void test131() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test131"); }


    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.0d, 0.0d);
    int i5 = interval2.checkPoint(0.0d, 0.0d);
    
    // Regression assertion (captures the current behavior of the code)
    org.junit.Assert.assertTrue(i5 == 0);

  }

  @Test
  public void test132() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test132"); }


    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.0d, 0.1d);
    int i5 = interval2.checkPoint(0.0d, 0.0d);
    
    // Regression assertion (captures the current behavior of the code)
    org.junit.Assert.assertTrue(i5 == 0);

  }

  @Test
  public void test133() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test133"); }


    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.1d, 0.1d);
    int i5 = interval2.checkPoint(0.0d, 0.0d);
    
    // Regression assertion (captures the current behavior of the code)
    org.junit.Assert.assertTrue(i5 == (-1));

  }

  @Test
  public void test134() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test134"); }


    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.0d, 0.2d);
    int i5 = interval2.checkPoint(0.0d, 0.0d);
    
    // Regression assertion (captures the current behavior of the code)
    org.junit.Assert.assertTrue(i5 == 0);

  }

  @Test
  public void test135() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test135"); }


    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.1d, 0.2d);
    int i5 = interval2.checkPoint(0.0d, 0.0d);
    
    // Regression assertion (captures the current behavior of the code)
    org.junit.Assert.assertTrue(i5 == (-1));

  }

  @Test
  public void test136() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test136"); }


    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.2d);
    int i5 = interval2.checkPoint(0.0d, 0.0d);
    
    // Regression assertion (captures the current behavior of the code)
    org.junit.Assert.assertTrue(i5 == (-1));

  }

  @Test
  public void test137() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test137"); }


    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.0d, 0.3d);
    int i5 = interval2.checkPoint(0.0d, 0.0d);
    
    // Regression assertion (captures the current behavior of the code)
    org.junit.Assert.assertTrue(i5 == 0);

  }

  @Test
  public void test138() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test138"); }


    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.1d, 0.3d);
    int i5 = interval2.checkPoint(0.0d, 0.0d);
    
    // Regression assertion (captures the current behavior of the code)
    org.junit.Assert.assertTrue(i5 == (-1));

  }

  @Test
  public void test139() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test139"); }


    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.2d, 0.3d);
    int i5 = interval2.checkPoint(0.0d, 0.0d);
    
    // Regression assertion (captures the current behavior of the code)
    org.junit.Assert.assertTrue(i5 == (-1));

  }

  @Test
  public void test140() throws Throwable {

    if (debug) { System.out.format("%n%s%n","IntervalcheckPoint4Suite0.test140"); }


    casestudies.commonsmath4.Interval interval2 = new casestudies.commonsmath4.Interval(0.3d, 0.3d);
    int i5 = interval2.checkPoint(0.0d, 0.0d);
    
    // Regression assertion (captures the current behavior of the code)
    org.junit.Assert.assertTrue(i5 == (-1));

  }

}
